name: CI

on:
  push:
    branches:
      - main
      - 'v*' # older version branches
    tags:
      - '*'

  pull_request: {}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install yarn
        run: npm install -g yarn
      - name: install dependencies
        run: yarn install
      - name: linting
        run: yarn lint

  test:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['14']

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: install yarn
        run: npm install -g yarn
      - name: install dependencies
        run: yarn install
      - name: test
        run: yarn test

  floating-test:
    name: Floating dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install yarn
        run: npm install -g yarn
      - name: install dependencies
        run: yarn install --no-lockfile
      - name: test
        run: yarn test
