name: CI

on:
  push:
    branches:
      - main
      - 'v*' # older version branches
    tags:
      - '*'

  pull_request: {}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - name: linting
        run: yarn lint

  test:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['16']

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - name: test
        run: yarn test

  floating-test:
    name: Floating dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm install --no-lockfile
      - name: test
        run: yarn test
